#!/usr/bin/env bash

set -o nounset
set -o errexit

usage() { echo "Usage: $0 [-u] PROJECT" 1>&2; exit 1; }

src=${ARCHIVE_DIR:?"ARCHIVE_DIR must be set to default archive directory"}
dst=${PROJECT_DIR:?"PROJECT_DIR must be set to default project directory"}
prj=$1

if [[ $1 = "-u" ]]; then
    tmp=$src; src=$dst; dst=$tmp
    prj=$2
fi

if [[ ! -e "$src/$prj" ]]; then
    echo "Project doesn't exist: $src/$prj"
    usage
fi

mv "$src/$prj" $dst

exit
